- hosts: '{{ target }}'
  tasks:
    - name: Install AOFlagger apt dependencies.
      sudo: yes
      action: apt pkg={{item}} state=installed
#      debug: msg="Would install {{ item }}"
      with_items: "{{ lookup('file', './aoflagger-deps-list.txt').split() }}"


    


