- hosts: '{{ target }}'  
  vars: 
    aoflagger_apt_deps: "{{ lookup('file', './aoflagger-deps-list.txt').split() }}"

  tasks:
#  - name: Print list of packages
#    debug: msg="Would install {{item}}"
#    with_items: aoflagger_apt_deps
#    tags: debug

  - name: Install AOFlagger apt dependencies.
    sudo: yes
    action: apt pkg={{item}} state=installed
    with_items: aoflagger_apt_deps




    


